language: perl
perl:
    - "5.24"
    - "blead"

matrix:
    include:
        - perl: "5.24"
          env: COVERAGE=1 MYSQL_VERSION=5.7
    allow_failures:
        - perl: "blead"
          env: MYSQL_VERSION=5.7

before_install:
    - if [ x"$MYSQL_VERSION" != "x" ];
      then
        sudo service mysql stop;
        sudo aptitude purge -y mysql-server libmysqlclient-dev mysql-server-5.6 mysql-common-5.6 mysql-client-5.6 libmysqlclient18 mysql-client-core-5.6 mysql-server-core-5.6 libdbd-mysql-perl mysql-common;
        sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5;
        . /etc/lsb-release;
        sudo add-apt-repository "deb http://repo.mysql.com/apt/ubuntu/ $DISTRIB_CODENAME mysql-$MYSQL_VERSION";
        sudo apt-get update;
        sudo DEBIAN_FRONTEND=noninteractive apt-get -q --yes --fix-broken --allow-unauthenticated --option DPkg::Options::=--force-confnew install mysql-server libmysqlclient-dev;
        sudo mysql_upgrade -u root --password='' --force;
        sudo service mysql restart;
      fi
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR

install:
    - cpan-install --deps
    - cpan-install --coverage

before_script:
    - coverage-setup

script:
    - perl Makefile.PL
    - make
    - prove -bl -s -j$(test-jobs) $(test-files)

after_success:
    - coverage-report
